### PR TITLE
doit 0.35.0

### PR DESCRIPTION
**Pull request by sayantikabanik**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by sayantikabanik** [comment]
@conda-forge-admin, please rerender

**Comment by rgommers** [comment]
Looks like this needs a few more changes @sayantikabanik:
```
ERROR: Package 'doit' requires a different Python: 3.7.12 not in '>=3.8'
```

The recipe should be updated to say `python >= 3.8` in multiple places, e.g.: https://github.com/conda-forge/doit-feedstock/blob/main/recipe/meta.yaml#L73

**Comment by sayantikabanik** [comment]
@conda-forge-admin, please rerender

**Comment by bollwyvl** [comment]
Thanks!

Yeah, it's kinda picky: for non-no-arch builds, you only get to say `python` and have to do the rest with e.g.

```
build:
  skip: true  # [py<38]
```

I think i can patch it up for you.

**Comment by bollwyvl** [comment]
@conda-forge-admin, please rerender

**Comment by bollwyvl** [comment]
Ah, i did it wrong: even though it worked, the `noarch` packages need to keep the python pin

**Comment by bollwyvl** [comment]
@conda-forge-admin, please rerender

**Comment by rgommers** [comment]
Wow that is fiddly indeed.

**Comment by bollwyvl** [comment]
>  fiddly indeed

yep. the conditional dependencies hurt. i sure wish that the `auto` stuff (`inotify`, etc) were optional so that this whole thing could be `noarch: python`. 

semi-related: we now have the ability to do multiple noarch builds on different platforms (e.g. depending on `__unix`), but i haven't looked into it yet for this package.

**Comment by bollwyvl** [comment]
Thanks all!

**Pull request merged**
